# Project Information
site_name: Kyya Wiki
site_description: Kyya Wiki
site_author: Kyya

# Copyright
copyright: "Copyright &copy; 2020 Kyya"

# Theme
theme:
  name: "material"
  language: "zh"
  palette:
    primary: "white"
    accent: "red"
  icon:
    logo: "material/school"
  features:
    - tabs
  font:
    text: Noto Sans
    code: Source Code Pro
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

# Repository
repo_name: "Kyya/Wiki"
repo_url: "https://github.com/Kyya/Wiki"
edit_uri: "blob/master/docs/"

# Customization
extra:
  copyright: "CC BY-NC-SA 4.0"

nav:
  - JS L2 Position:
      - Getting Started: JS-L2-Position/index.md
      - Maturity (Experience, Years): JS-L2-Position/maturity.md
      - Tech Expertise: JS-L2-Position/tech-expertise.md
      - Design Thinking and Documentation Skills: JS-L2-Position/design-thinking-and-documentation-skills.md
      - Quality, ENGX: JS-L2-Position/quality-and-engx.md
      - Software Development Process Knowledge: JS-L2-Position/software-development-process-knowledge.md
      - Roles Played on a Project, Leadership, Soft Skills: JS-L2-Position/roles-played-on-a-project-leadership-and-soft-skills.md
      - Non-project Organizational Influence: JS-L2-Position/non-project-organizational-influence.md
      - English Language: JS-L2-Position/english-language.md